# Generated by Django 2.2.4 on 2024-06-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240607_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
